apiVersion: gateway.k8s.aws/v1beta1
kind: LoadBalancerConfiguration
metadata:
  name: docket-staging-alb-config
  namespace: staging-frontend
spec:
  loadBalancerName: docket-staging-gateway
  scheme: internet-facing
  ipAddressType: ipv4
  tags:
    Environment: staging
    ManagedBy: ArgoCD
    Project: Sintratel-Docket
