apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-log-message-processor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Sintratel-Docket/gitops-manifests.git
    targetRevision: main
    path: staging/log-message-processor
  destination:
    name: docket-staging
    namespace: staging-log-message-processor
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
