apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-users-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Sintratel-Docket/gitops-manifests.git
    targetRevision: main
    path: staging/users-api
  destination:
    name: docket-staging
    namespace: staging-users-api
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
