apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-api
  namespace: dev-auth-api
  labels:
    observability.sintratel.io/scrape: "true"
spec:
  selector:
    matchLabels:
      app: auth-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s

