apiVersion: v1
kind: Service
metadata:
  name: todos-api
  namespace: prod-todos-api
spec:
  type: ClusterIP
  selector:
    app: todos-api
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
