apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-auth-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Sintratel-Docket/gitops-manifests.git
    targetRevision: main
    path: prod/auth-api
  destination:
    name: docket-prod
    namespace: prod-auth-api
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
