apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-message-processor
  namespace: dev-log-message-processor
  labels:
    app: log-message-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-message-processor
  template:
    metadata:
      labels:
        app: log-message-processor
      annotations:
        gitops.sintratel.io/reconciliation-marker: baseline
    spec:
      containers:
        - name: log-message-processor
          image: 429418377318.dkr.ecr.us-east-1.amazonaws.com/docket/log-message-processor:1.0.0-165ae2a
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_HOST
              value: redis.dev-todos-api.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_CHANNEL
              value: log_channel
            - name: METRICS_PORT
              value: "9100"
          ports:
            - name: metrics
              containerPort: 9100
              protocol: TCP
