apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 89.2.1
      helm:
        releaseName: observability
        valueFiles:
          - $values/dev/observability/values.yaml
    - repoURL: https://github.com/Sintratel-Docket/gitops-manifests.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/Sintratel-Docket/gitops-manifests.git
      targetRevision: main
      path: dev/observability/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-observability
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true

