apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbac
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Sintratel-Docket/gitops-manifests.git
    targetRevision: main
    path: dev/rbac
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system # nominal; los ClusterRoleBinding son cluster-scoped
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
